### ISSUE TITLE
Not an issue. Build schedule 

### ISSUE THREAD

**Issue by fire1ce** [vegardit/docker-traefik-logrotate#7]
Any reason you build new container on daily basis? I think it’s more propitiate to push new images ones a week if there were no code change. I have my containers with automatic update with new images. Yours updates every single day.

**Comment by sebthom** [comment]
I am trying to keep the images up-to-date with security fixes and since I don't know when new ones are released I am rebuilding the image daily. But nothing prevents you from updating your containers only once a week.

**Comment by fire1ce** [comment]
@sebthom thanks for the replay. 
Since your container doesn't even listening on a single port and have access to specific folder you can build it ones a week. even [LinuxServer.io](https://www.linuxserver.io/) updates there containers ones a week. 
But its your baby, to its your chose. Thanks for the job u did!
